/* eslint-disable import/prefer-default-export */
import { MigrationInterface, QueryRunner } from 'typeorm';

export class PopularDB1617318543036 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `
      set IDENTITY_INSERT School ON
INSERT INTO [dbo].[School]([id],[name],[description],[street],[neighborhood],[city],[state])
VALUES(1,'E.M.E.F Gilmar Taccola','E.M.E.F Gilmar Taccola','R. Lutécia, 1730','Vila Carrão','São Paulo','SP')
INSERT INTO [dbo].[School]([id],[name],[description],[street],[neighborhood],[city],[state])
VALUES(2,'Emei Alberto Mesquita De Camargo, Prof.','Emei Alberto Mesquita De Camargo, Prof.','Praça Barão Homem de Melo, S/N','Vila Carrão','São Paulo','SP')
INSERT INTO [dbo].[School]([id],[name],[description],[street],[neighborhood],[city],[state])
VALUES(3,'Escola Estadual Professor Salvador Rocco','Escola Estadual Professor Salvador Rocco','R. Renato Rinaldi, 31','Vila Carrão','São Paulo','SP')
INSERT INTO [dbo].[School]([id],[name],[description],[street],[neighborhood],[city],[state])
VALUES(4,'EE Prof° Irene Ribeiro','EE Prof° Irene Ribeiro','R. Cel. Amaro Sobrinho, 303','Vila Carrão','São Paulo','SP')
INSERT INTO [dbo].[School]([id],[name],[description],[street],[neighborhood],[city],[state])
VALUES(5,'Escola Estadual Dom Bernardo Rodrigues Nogueira','Escola Estadual Dom Bernardo Rodrigues Nogueira','R. Dom João Maria Ogno, 486','Vila Matilde','São Paulo','SP')
INSERT INTO [dbo].[School]([id],[name],[description],[street],[neighborhood],[city],[state])
VALUES(6,'E. E. Infante Dom Henrique','E. E. Infante Dom Henrique','R. Teodoro Mascarenhas, 133','Vila Matilde','São Paulo','SP')
INSERT INTO [dbo].[School]([id],[name],[description],[street],[neighborhood],[city],[state])
VALUES(7,'EMEF Pres João Pinheiro','EMEF Pres João Pinheiro','R. Dr. Edgar García Viêira, 140','Vila Matilde','São Paulo','SP')
INSERT INTO [dbo].[School]([id],[name],[description],[street],[neighborhood],[city],[state])
VALUES(8,'Emei Suzana Evangelina Felippe, Profa.','Emei Suzana Evangelina Felippe, Profa.','Praça Haroldo Daltro, S/N','Vila Nova Manchester','São Paulo','SP')
INSERT INTO [dbo].[School]([id],[name],[description],[street],[neighborhood],[city],[state])
VALUES(9,'Escola Estadual Coronel Pedro Arbues','Escola Estadual Coronel Pedro Arbues','R. Lucinda Gomes Barreto, 605','Vila Nova Manchester','São Paulo','SP')
INSERT INTO [dbo].[School]([id],[name],[description],[street],[neighborhood],[city],[state])
VALUES(10,'EMEF Guimarães Rosa','EMEF Guimarães Rosa','Praça Haroldo Daltro, 466','Vila Nova Manchester','São Paulo','SP')
INSERT INTO [dbo].[School]([id],[name],[description],[street],[neighborhood],[city],[state])
VALUES(11,'Escola Municipal Suzana Evangelina Felippe','Escola Municipal Suzana Evangelina Felippe','Pca Haroldo Daltro','Vila Nova Manchester','São Paulo','SP')
INSERT INTO [dbo].[School]([id],[name],[description],[street],[neighborhood],[city],[state])
VALUES(12,'Guilherme A D Oliveira','Guilherme A D Oliveira','R. Carlos Silva, 90','Chácara Califórnia','São Paulo','SP')
INSERT INTO [dbo].[School]([id],[name],[description],[street],[neighborhood],[city],[state])
VALUES(13,'Escola Estadual Professor Alvino Bittencourt','Escola Estadual Professor Alvino Bittencourt','R. Francisco Machado de Campos, 312','Chácara Califórnia','São Paulo','SP')
set IDENTITY_INSERT School OFF

set IDENTITY_INSERT PaperStore ON
INSERT INTO PaperStore([id],[name],[description],[email],[password],[balance],[street],[neighborhood],[city],[state])
	VALUES(1,'Papelaria Difrapel','Papelaria Difrapel','dipfrapel@gmail.com','$2b$08$ifezMmA6BjrLsFBVSlHJ3unL8Q7NOtIm4P4PQ6EOS9jkSFRF6TLwi',0,'Av. Dezenove de Janeiro, 481','Vila Carrão','São Paulo','SP')
INSERT INTO PaperStore([id],[name],[description],[email],[password],[balance],[street],[neighborhood],[city],[state])
	VALUES(2,'Mini Stop Papelaria & Presentes','Mini Stop Papelaria & Presentes','ministop@gmail.com','$2b$08$ifezMmA6BjrLsFBVSlHJ3unL8Q7NOtIm4P4PQ6EOS9jkSFRF6TLwi',0,'Av. Guilherme Giorgi, 227','Vila Carrão','São Paulo','SP')
INSERT INTO PaperStore([id],[name],[description],[email],[password],[balance],[street],[neighborhood],[city],[state])
	VALUES(3,'Bazar e Papelaria Nova Carrão','Bazar e Papelaria Nova Carrão','novacarrao@gmail.com','$2b$08$ifezMmA6BjrLsFBVSlHJ3unL8Q7NOtIm4P4PQ6EOS9jkSFRF6TLwi',0,'Av. Conselheiro Carrão','Vila Carrão','São Paulo','SP')
INSERT INTO PaperStore([id],[name],[description],[email],[password],[balance],[street],[neighborhood],[city],[state])
	VALUES(4,'Premium Papelaria','Premium Papelaria','premium@gmail.com','$2b$08$ifezMmA6BjrLsFBVSlHJ3unL8Q7NOtIm4P4PQ6EOS9jkSFRF6TLwi',0,'R. José Mascarenhas, 1244','Vila Matilde','São Paulo','SP')
INSERT INTO PaperStore([id],[name],[description],[email],[password],[balance],[street],[neighborhood],[city],[state])
	VALUES(5,'C-Lig Papelaria','C-Lig Papelaria','clig@gmail.com','$2b$08$ifezMmA6BjrLsFBVSlHJ3unL8Q7NOtIm4P4PQ6EOS9jkSFRF6TLwi',0,'R. Dona Matilde, 741','Vila Matilde','São Paulo','SP')
INSERT INTO PaperStore([id],[name],[description],[email],[password],[balance],[street],[neighborhood],[city],[state])
	VALUES(6,'Bazar Pimentel','Bazar Pimentel','pimentel@gmail.com','$2b$08$ifezMmA6BjrLsFBVSlHJ3unL8Q7NOtIm4P4PQ6EOS9jkSFRF6TLwi',0,'R. José Mascarenhas, 490','Vila Matilde','São Paulo','SP')
INSERT INTO PaperStore([id],[name],[description],[email],[password],[balance],[street],[neighborhood],[city],[state])
	VALUES(7,'Papelaria Império','Papelaria Império','imperio@gmail.com','$2b$08$ifezMmA6BjrLsFBVSlHJ3unL8Q7NOtIm4P4PQ6EOS9jkSFRF6TLwi',0,'Praça Haroldo Daltro, 70','Vila Nova Manchester','São Paulo','SP')
INSERT INTO PaperStore([id],[name],[description],[email],[password],[balance],[street],[neighborhood],[city],[state])
	VALUES(8,'Loja Momotaro','Loja Momotaro','momotaro@gmail.com','$2b$08$ifezMmA6BjrLsFBVSlHJ3unL8Q7NOtIm4P4PQ6EOS9jkSFRF6TLwi',0,'Av. Lins de Vasconcelos, 2747','Vila Nova Manchester','São Paulo','SP')
INSERT INTO PaperStore([id],[name],[description],[email],[password],[balance],[street],[neighborhood],[city],[state])
	VALUES(9,'AlphaGraphics','AlphaGraphics','alphagraphics@gmail.com','$2b$08$ifezMmA6BjrLsFBVSlHJ3unL8Q7NOtIm4P4PQ6EOS9jkSFRF6TLwi',0,'Av. dos Bandeirantes, 5583','Vila Nova Manchester','São Paulo','SP')
INSERT INTO PaperStore([id],[name],[description],[email],[password],[balance],[street],[neighborhood],[city],[state])
	VALUES(10,'PAPELARIA E AVIMENTOS','PAPELARIA E AVIMENTOS','papelariaaviamentos@gmail.com','$2b$08$ifezMmA6BjrLsFBVSlHJ3unL8Q7NOtIm4P4PQ6EOS9jkSFRF6TLwi',0,'Rua Comendador Gil Pinheiro, 444','Chácara Califórnia','São Paulo','SP')
set IDENTITY_INSERT PaperStore OFF


set IDENTITY_INSERT Product ON
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(1,'Apontador com depósito - 2 unidades','Apontador com depósito - 2 unidades','https://images-americanas.b2w.io/produtos/01/00/img/1440477/5/1440477507_1GG.jpg',5,1)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(2,'Borracha escolar - 2 unidades','Borracha escolar - 2 unidades','https://images-americanas.b2w.io/produtos/01/00/img/1257224/0/1257224085_1GG.jpg',1,1)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(3,'Caderno 15 materias','Caderno 15 materias','https://img.kalunga.com.br/fotosdeprodutos/136493d.jpg',18.9,1)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(4,'Caderno de desenho 96 folhas','Caderno de desenho 96 folhas','https://img.kalunga.com.br/fotosdeprodutos/101419d.jpg',8.9,1)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(5,'Régua 30 cm','Régua 30 cm','https://img.kalunga.com.br/fotosdeprodutos/662417d.jpg',2.6,1)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(6,'Canetinha hidrográfica (12 cores)','Canetinha hidrográfica (12 cores)','https://img.kalunga.com.br/fotosdeprodutos/189191d.jpg',8.9,1)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(7,'Cola branca 90g','Cola branca 90g','https://img.kalunga.com.br/fotosdeprodutos/214602d.jpg',3.5,1)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(8,'Papel Sufite - 100 folhas','Papel Sufite - 100 folhas','https://img.kalunga.com.br/fotosdeprodutos/478167z.jpg',4,1)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(9,'Lápis de cor (12 cores)','Lápis de cor (12 cores)','https://img.kalunga.com.br/fotosdeprodutos/389505d.jpg',16,1)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(10,'Lápis grafite - 4 unidades','Lápis grafite - 4 unidades','https://img.kalunga.com.br/fotosdeprodutos/410702d.jpg',4,1)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(11,'Canetas','Canetas','https://img.kalunga.com.br/fotosdeprodutos/176022d.jpg',4.5,1)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(12,'Tesoura sem ponta','Tesoura sem ponta','https://img.kalunga.com.br/fotosdeprodutos/675312d.jpg',4,1)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(13,'Apontador com depósito - 2 unidades','Apontador com depósito - 2 unidades','https://images-americanas.b2w.io/produtos/01/00/img/1440477/5/1440477507_1GG.jpg',5,2)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(14,'Borracha escolar - 2 unidades','Borracha escolar - 2 unidades','https://images-americanas.b2w.io/produtos/01/00/img/1257224/0/1257224085_1GG.jpg',1,2)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(15,'Caderno 15 materias','Caderno 15 materias','https://img.kalunga.com.br/fotosdeprodutos/136493d.jpg',18.9,2)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(16,'Caderno de desenho 96 folhas','Caderno de desenho 96 folhas','https://img.kalunga.com.br/fotosdeprodutos/101419d.jpg',8.9,2)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(17,'Régua 30 cm','Régua 30 cm','https://img.kalunga.com.br/fotosdeprodutos/662417d.jpg',2.6,2)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(18,'Canetinha hidrográfica (12 cores)','Canetinha hidrográfica (12 cores)','https://img.kalunga.com.br/fotosdeprodutos/189191d.jpg',8.9,2)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(19,'Cola branca 90g','Cola branca 90g','https://img.kalunga.com.br/fotosdeprodutos/214602d.jpg',3.5,2)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(20,'Papel Sufite - 100 folhas','Papel Sufite - 100 folhas','https://img.kalunga.com.br/fotosdeprodutos/478167z.jpg',4,2)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(21,'Lápis de cor (12 cores)','Lápis de cor (12 cores)','https://img.kalunga.com.br/fotosdeprodutos/389505d.jpg',16,2)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(22,'Lápis grafite - 4 unidades','Lápis grafite - 4 unidades','https://img.kalunga.com.br/fotosdeprodutos/410702d.jpg',4,2)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(23,'Canetas','Canetas','https://img.kalunga.com.br/fotosdeprodutos/176022d.jpg',4.5,2)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(24,'Tesoura sem ponta','Tesoura sem ponta','https://img.kalunga.com.br/fotosdeprodutos/675312d.jpg',4,2)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(25,'Apontador com depósito - 2 unidades','Apontador com depósito - 2 unidades','https://images-americanas.b2w.io/produtos/01/00/img/1440477/5/1440477507_1GG.jpg',5,3)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(26,'Borracha escolar - 2 unidades','Borracha escolar - 2 unidades','https://images-americanas.b2w.io/produtos/01/00/img/1257224/0/1257224085_1GG.jpg',1,3)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(27,'Caderno 15 materias','Caderno 15 materias','https://img.kalunga.com.br/fotosdeprodutos/136493d.jpg',18.9,3)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(28,'Caderno de desenho 96 folhas','Caderno de desenho 96 folhas','https://img.kalunga.com.br/fotosdeprodutos/101419d.jpg',8.9,3)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(29,'Régua 30 cm','Régua 30 cm','https://img.kalunga.com.br/fotosdeprodutos/662417d.jpg',2.6,3)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(30,'Canetinha hidrográfica (12 cores)','Canetinha hidrográfica (12 cores)','https://img.kalunga.com.br/fotosdeprodutos/189191d.jpg',8.9,3)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(31,'Cola branca 90g','Cola branca 90g','https://img.kalunga.com.br/fotosdeprodutos/214602d.jpg',3.5,3)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(32,'Papel Sufite - 100 folhas','Papel Sufite - 100 folhas','https://img.kalunga.com.br/fotosdeprodutos/478167z.jpg',4,3)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(33,'Lápis de cor (12 cores)','Lápis de cor (12 cores)','https://img.kalunga.com.br/fotosdeprodutos/389505d.jpg',16,3)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(34,'Lápis grafite - 4 unidades','Lápis grafite - 4 unidades','https://img.kalunga.com.br/fotosdeprodutos/410702d.jpg',4,3)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(35,'Canetas','Canetas','https://img.kalunga.com.br/fotosdeprodutos/176022d.jpg',4.5,3)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(36,'Tesoura sem ponta','Tesoura sem ponta','https://img.kalunga.com.br/fotosdeprodutos/675312d.jpg',4,3)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(37,'Apontador com depósito - 2 unidades','Apontador com depósito - 2 unidades','https://images-americanas.b2w.io/produtos/01/00/img/1440477/5/1440477507_1GG.jpg',5,4)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(38,'Borracha escolar - 2 unidades','Borracha escolar - 2 unidades','https://images-americanas.b2w.io/produtos/01/00/img/1257224/0/1257224085_1GG.jpg',1,4)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(39,'Caderno 15 materias','Caderno 15 materias','https://img.kalunga.com.br/fotosdeprodutos/136493d.jpg',18.9,4)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(40,'Caderno de desenho 96 folhas','Caderno de desenho 96 folhas','https://img.kalunga.com.br/fotosdeprodutos/101419d.jpg',8.9,4)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(41,'Régua 30 cm','Régua 30 cm','https://img.kalunga.com.br/fotosdeprodutos/662417d.jpg',2.6,4)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(42,'Canetinha hidrográfica (12 cores)','Canetinha hidrográfica (12 cores)','https://img.kalunga.com.br/fotosdeprodutos/189191d.jpg',8.9,4)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(43,'Cola branca 90g','Cola branca 90g','https://img.kalunga.com.br/fotosdeprodutos/214602d.jpg',3.5,4)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(44,'Papel Sufite - 100 folhas','Papel Sufite - 100 folhas','https://img.kalunga.com.br/fotosdeprodutos/478167z.jpg',4,4)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(45,'Lápis de cor (12 cores)','Lápis de cor (12 cores)','https://img.kalunga.com.br/fotosdeprodutos/389505d.jpg',16,4)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(46,'Lápis grafite - 4 unidades','Lápis grafite - 4 unidades','https://img.kalunga.com.br/fotosdeprodutos/410702d.jpg',4,4)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(47,'Canetas','Canetas','https://img.kalunga.com.br/fotosdeprodutos/176022d.jpg',4.5,4)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(48,'Tesoura sem ponta','Tesoura sem ponta','https://img.kalunga.com.br/fotosdeprodutos/675312d.jpg',4,4)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(49,'Apontador com depósito - 2 unidades','Apontador com depósito - 2 unidades','https://images-americanas.b2w.io/produtos/01/00/img/1440477/5/1440477507_1GG.jpg',5,5)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(50,'Borracha escolar - 2 unidades','Borracha escolar - 2 unidades','https://images-americanas.b2w.io/produtos/01/00/img/1257224/0/1257224085_1GG.jpg',1,5)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(51,'Caderno 15 materias','Caderno 15 materias','https://img.kalunga.com.br/fotosdeprodutos/136493d.jpg',18.9,5)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(52,'Caderno de desenho 96 folhas','Caderno de desenho 96 folhas','https://img.kalunga.com.br/fotosdeprodutos/101419d.jpg',8.9,5)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(53,'Régua 30 cm','Régua 30 cm','https://img.kalunga.com.br/fotosdeprodutos/662417d.jpg',2.6,5)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(54,'Canetinha hidrográfica (12 cores)','Canetinha hidrográfica (12 cores)','https://img.kalunga.com.br/fotosdeprodutos/189191d.jpg',8.9,5)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(55,'Cola branca 90g','Cola branca 90g','https://img.kalunga.com.br/fotosdeprodutos/214602d.jpg',3.5,5)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(56,'Papel Sufite - 100 folhas','Papel Sufite - 100 folhas','https://img.kalunga.com.br/fotosdeprodutos/478167z.jpg',4,5)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(57,'Lápis de cor (12 cores)','Lápis de cor (12 cores)','https://img.kalunga.com.br/fotosdeprodutos/389505d.jpg',16,5)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(58,'Lápis grafite - 4 unidades','Lápis grafite - 4 unidades','https://img.kalunga.com.br/fotosdeprodutos/410702d.jpg',4,5)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(59,'Canetas','Canetas','https://img.kalunga.com.br/fotosdeprodutos/176022d.jpg',4.5,5)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(60,'Tesoura sem ponta','Tesoura sem ponta','https://img.kalunga.com.br/fotosdeprodutos/675312d.jpg',4,5)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(61,'Apontador com depósito - 2 unidades','Apontador com depósito - 2 unidades','https://images-americanas.b2w.io/produtos/01/00/img/1440477/5/1440477507_1GG.jpg',5,6)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(62,'Borracha escolar - 2 unidades','Borracha escolar - 2 unidades','https://images-americanas.b2w.io/produtos/01/00/img/1257224/0/1257224085_1GG.jpg',1,6)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(63,'Caderno 15 materias','Caderno 15 materias','https://img.kalunga.com.br/fotosdeprodutos/136493d.jpg',18.9,6)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(64,'Caderno de desenho 96 folhas','Caderno de desenho 96 folhas','https://img.kalunga.com.br/fotosdeprodutos/101419d.jpg',8.9,6)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(65,'Régua 30 cm','Régua 30 cm','https://img.kalunga.com.br/fotosdeprodutos/662417d.jpg',2.6,6)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(66,'Canetinha hidrográfica (12 cores)','Canetinha hidrográfica (12 cores)','https://img.kalunga.com.br/fotosdeprodutos/189191d.jpg',8.9,6)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(67,'Cola branca 90g','Cola branca 90g','https://img.kalunga.com.br/fotosdeprodutos/214602d.jpg',3.5,6)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(68,'Papel Sufite - 100 folhas','Papel Sufite - 100 folhas','https://img.kalunga.com.br/fotosdeprodutos/478167z.jpg',4,6)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(69,'Lápis de cor (12 cores)','Lápis de cor (12 cores)','https://img.kalunga.com.br/fotosdeprodutos/389505d.jpg',16,6)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(70,'Lápis grafite - 4 unidades','Lápis grafite - 4 unidades','https://img.kalunga.com.br/fotosdeprodutos/410702d.jpg',4,6)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(71,'Canetas','Canetas','https://img.kalunga.com.br/fotosdeprodutos/176022d.jpg',4.5,6)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(72,'Tesoura sem ponta','Tesoura sem ponta','https://img.kalunga.com.br/fotosdeprodutos/675312d.jpg',4,6)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(73,'Apontador com depósito - 2 unidades','Apontador com depósito - 2 unidades','https://images-americanas.b2w.io/produtos/01/00/img/1440477/5/1440477507_1GG.jpg',5,7)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(74,'Borracha escolar - 2 unidades','Borracha escolar - 2 unidades','https://images-americanas.b2w.io/produtos/01/00/img/1257224/0/1257224085_1GG.jpg',1,7)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(75,'Caderno 15 materias','Caderno 15 materias','https://img.kalunga.com.br/fotosdeprodutos/136493d.jpg',18.9,7)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(76,'Caderno de desenho 96 folhas','Caderno de desenho 96 folhas','https://img.kalunga.com.br/fotosdeprodutos/101419d.jpg',8.9,7)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(77,'Régua 30 cm','Régua 30 cm','https://img.kalunga.com.br/fotosdeprodutos/662417d.jpg',2.6,7)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(78,'Canetinha hidrográfica (12 cores)','Canetinha hidrográfica (12 cores)','https://img.kalunga.com.br/fotosdeprodutos/189191d.jpg',8.9,7)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(79,'Cola branca 90g','Cola branca 90g','https://img.kalunga.com.br/fotosdeprodutos/214602d.jpg',3.5,7)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(80,'Papel Sufite - 100 folhas','Papel Sufite - 100 folhas','https://img.kalunga.com.br/fotosdeprodutos/478167z.jpg',4,7)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(81,'Lápis de cor (12 cores)','Lápis de cor (12 cores)','https://img.kalunga.com.br/fotosdeprodutos/389505d.jpg',16,7)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(82,'Lápis grafite - 4 unidades','Lápis grafite - 4 unidades','https://img.kalunga.com.br/fotosdeprodutos/410702d.jpg',4,7)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(83,'Canetas','Canetas','https://img.kalunga.com.br/fotosdeprodutos/176022d.jpg',4.5,7)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(84,'Tesoura sem ponta','Tesoura sem ponta','https://img.kalunga.com.br/fotosdeprodutos/675312d.jpg',4,7)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(85,'Apontador com depósito - 2 unidades','Apontador com depósito - 2 unidades','https://images-americanas.b2w.io/produtos/01/00/img/1440477/5/1440477507_1GG.jpg',5,8)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(86,'Borracha escolar - 2 unidades','Borracha escolar - 2 unidades','https://images-americanas.b2w.io/produtos/01/00/img/1257224/0/1257224085_1GG.jpg',1,8)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(87,'Caderno 15 materias','Caderno 15 materias','https://img.kalunga.com.br/fotosdeprodutos/136493d.jpg',18.9,8)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(88,'Caderno de desenho 96 folhas','Caderno de desenho 96 folhas','https://img.kalunga.com.br/fotosdeprodutos/101419d.jpg',8.9,8)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(89,'Régua 30 cm','Régua 30 cm','https://img.kalunga.com.br/fotosdeprodutos/662417d.jpg',2.6,8)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(90,'Canetinha hidrográfica (12 cores)','Canetinha hidrográfica (12 cores)','https://img.kalunga.com.br/fotosdeprodutos/189191d.jpg',8.9,8)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(91,'Cola branca 90g','Cola branca 90g','https://img.kalunga.com.br/fotosdeprodutos/214602d.jpg',3.5,8)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(92,'Papel Sufite - 100 folhas','Papel Sufite - 100 folhas','https://img.kalunga.com.br/fotosdeprodutos/478167z.jpg',4,8)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(93,'Lápis de cor (12 cores)','Lápis de cor (12 cores)','https://img.kalunga.com.br/fotosdeprodutos/389505d.jpg',16,8)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(94,'Lápis grafite - 4 unidades','Lápis grafite - 4 unidades','https://img.kalunga.com.br/fotosdeprodutos/410702d.jpg',4,8)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(95,'Canetas','Canetas','https://img.kalunga.com.br/fotosdeprodutos/176022d.jpg',4.5,8)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(96,'Tesoura sem ponta','Tesoura sem ponta','https://img.kalunga.com.br/fotosdeprodutos/675312d.jpg',4,8)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(97,'Apontador com depósito - 2 unidades','Apontador com depósito - 2 unidades','https://images-americanas.b2w.io/produtos/01/00/img/1440477/5/1440477507_1GG.jpg',5,9)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(98,'Borracha escolar - 2 unidades','Borracha escolar - 2 unidades','https://images-americanas.b2w.io/produtos/01/00/img/1257224/0/1257224085_1GG.jpg',1,9)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(99,'Caderno 15 materias','Caderno 15 materias','https://img.kalunga.com.br/fotosdeprodutos/136493d.jpg',18.9,9)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(100,'Caderno de desenho 96 folhas','Caderno de desenho 96 folhas','https://img.kalunga.com.br/fotosdeprodutos/101419d.jpg',8.9,9)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(101,'Régua 30 cm','Régua 30 cm','https://img.kalunga.com.br/fotosdeprodutos/662417d.jpg',2.6,9)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(102,'Canetinha hidrográfica (12 cores)','Canetinha hidrográfica (12 cores)','https://img.kalunga.com.br/fotosdeprodutos/189191d.jpg',8.9,9)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(103,'Cola branca 90g','Cola branca 90g','https://img.kalunga.com.br/fotosdeprodutos/214602d.jpg',3.5,9)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(104,'Papel Sufite - 100 folhas','Papel Sufite - 100 folhas','https://img.kalunga.com.br/fotosdeprodutos/478167z.jpg',4,9)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(105,'Lápis de cor (12 cores)','Lápis de cor (12 cores)','https://img.kalunga.com.br/fotosdeprodutos/389505d.jpg',16,9)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(106,'Lápis grafite - 4 unidades','Lápis grafite - 4 unidades','https://img.kalunga.com.br/fotosdeprodutos/410702d.jpg',4,9)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(107,'Canetas','Canetas','https://img.kalunga.com.br/fotosdeprodutos/176022d.jpg',4.5,9)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(108,'Tesoura sem ponta','Tesoura sem ponta','https://img.kalunga.com.br/fotosdeprodutos/675312d.jpg',4,9)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(109,'Apontador com depósito - 2 unidades','Apontador com depósito - 2 unidades','https://images-americanas.b2w.io/produtos/01/00/img/1440477/5/1440477507_1GG.jpg',5,10)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(110,'Borracha escolar - 2 unidades','Borracha escolar - 2 unidades','https://images-americanas.b2w.io/produtos/01/00/img/1257224/0/1257224085_1GG.jpg',1,10)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(111,'Caderno 15 materias','Caderno 15 materias','https://img.kalunga.com.br/fotosdeprodutos/136493d.jpg',18.9,10)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(112,'Caderno de desenho 96 folhas','Caderno de desenho 96 folhas','https://img.kalunga.com.br/fotosdeprodutos/101419d.jpg',8.9,10)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(113,'Régua 30 cm','Régua 30 cm','https://img.kalunga.com.br/fotosdeprodutos/662417d.jpg',2.6,10)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(114,'Canetinha hidrográfica (12 cores)','Canetinha hidrográfica (12 cores)','https://img.kalunga.com.br/fotosdeprodutos/189191d.jpg',8.9,10)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(115,'Cola branca 90g','Cola branca 90g','https://img.kalunga.com.br/fotosdeprodutos/214602d.jpg',3.5,10)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(116,'Papel Sufite - 100 folhas','Papel Sufite - 100 folhas','https://img.kalunga.com.br/fotosdeprodutos/478167z.jpg',4,10)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(117,'Lápis de cor (12 cores)','Lápis de cor (12 cores)','https://img.kalunga.com.br/fotosdeprodutos/389505d.jpg',16,10)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(118,'Lápis grafite - 4 unidades','Lápis grafite - 4 unidades','https://img.kalunga.com.br/fotosdeprodutos/410702d.jpg',4,10)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(119,'Canetas','Canetas','https://img.kalunga.com.br/fotosdeprodutos/176022d.jpg',4.5,10)
INSERT INTO Product ([id],[name],[description],[img_url],[price],[paperStoreId])
     VALUES(120,'Tesoura sem ponta','Tesoura sem ponta','https://img.kalunga.com.br/fotosdeprodutos/675312d.jpg',4,10)

set IDENTITY_INSERT Product OFF
      `,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`delete from product`);
    await queryRunner.query(`delete from school`);
    await queryRunner.query(`delete from paperStore`);
  }
}
